### ISSUE TITLE
Compiling question

### ISSUE THREAD

**Issue by act18xh** [freetdi/p17#1]
When I try to compile this project with a "make" command, it occurs an error like this picture, I really could not find the 'stx/btree_set.h', how can I solve this error?
<img width="572" alt="屏幕快照 2019-07-29 12 53 52" src="https://user-images.githubusercontent.com/43570482/62047112-8f46bd00-b201-11e9-9f0b-97f43db444fe.png">

**Comment by felix-salfelder** [comment]
On Mon, Jul 29, 2019 at 05:10:45AM -0700, act18xh wrote:
> When I try to compile this project with a "make" command, it occurs an
> error like this picture, I really could not find the
> 'stx/btree_set.h', how can I solve this error?

Hi.

On Debian, the header is in the "stx-btree-dev" package.

# apt install stx-btree-dev

NB: p17 is an archived snapshot. it is now part of treedec,
e.g. https://gitlab.com/freetdi/treedec.

**Comment by farhad-vadiee** [comment]
when I am compiling the program, It shows the following error:

`` ./tdlib/graph_traits.hpp: In function ‘unsigned int& boost::get(treedec::bagsize_t, G&)’:
./tdlib/graph_traits.hpp:46:30: error: cannot bind non-const lvalue reference of type ‘unsigned int&’ to an rvalue of type ‘unsigned int’
   46 |  return treedec::bagsize_t().dummy;``

Is it okay if I change ``unsigned int&`` to ``unsigned int``?

**Comment by felix-salfelder** [comment]
On Fri, Dec 10, 2021 at 01:30:09AM -0800, Farhad Vadiee wrote:
> when I am compiling the program, It shows the following error:
> 
> `` ./tdlib/graph_traits.hpp: In function ‘unsigned int& boost::get(treedec::bagsize_t, G&)’:
> ./tdlib/graph_traits.hpp:46:30: error: cannot bind non-const lvalue reference of type ‘unsigned int&’ to an rvalue of type ‘unsigned int’
>    46 |  return treedec::bagsize_t().dummy;``
> 
> Is it okay if I change ``unsigned int&`` to ``unsigned int``?

You can try this, and see if it works. I think the reference is not used
anywhere. (if it is, auto& might still do?)

p17 is only a snapshot and most of it has been merged back into treedec
(former tdlib) few years ago. perhaps have a look there.

thanks
felix

**Comment by pokorj54** [comment]
Could you please add that this is just snapshot of another project to the repository description. I would not found it if I wasn't looking into this issue. And it would save me some time.

**Comment by felix-salfelder** [comment]
You are welcome to look into this issue. The information you are looking for is in line 3 of the README file, and the second paragraph of the BUGS section therein.

The README file is at the root of the repository and on display on the github front page of the repo. Ignore whatever else they claim.
