### ISSUE TITLE
Compilation error in tdlib

### ISSUE THREAD

**Issue by BipedalMammalRescue** [freetdi/p17#3]
Hi, when I tried running make, I got the following error message from g++:

> In file included from ./tdlib/treedec_traits.hpp:27,
                 from ./tdlib/directed_view.hpp:27,
                 from ../../tdlib/grtd/grtd.cc:111:
./tdlib/graph_traits.hpp: In function ‘unsigned int& boost::get(treedec::bagsize_t, G&)’:
./tdlib/graph_traits.hpp:46:30: error: cannot bind non-const lvalue reference of type ‘unsigned int&’ to an rvalue of type ‘unsigned int’
   46 |  return treedec::bagsize_t().dummy;
      |                  ~~~~~~~~~~~~^~~~~
make[1]: *** [Makefile:579: grtd_profile-grtd.o] Error 1
make[1]: Leaving directory '/home/johnny/repos/p17/build/grtd'
make: *** [Makefile:18: grtd-stamp] Error 2

it seems changing that line to 
`auto result = treedec::bagsize_t().dummy; `
`return result;`
allowed the compilation to finish without error.

**Comment by felix-salfelder** [comment]
Thanks.
It has been fixed upstream. Also cf. issue #1. (This is a snapshot only).
